<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE model [
        <!ELEMENT model (palette|colorkeys|spritemap|layers|logic)*>
        <!ATTLIST model
                name CDATA #REQUIRED
                dir CDATA #REQUIRED
                width CDATA #REQUIRED
                height CDATA #REQUIRED
                scale CDATA #REQUIRED
                originX CDATA #IMPLIED
                originY CDATA #IMPLIED>
        <!ELEMENT palette (common|property)*>
        <!ELEMENT common (color)*>
        <!ELEMENT color (#PCDATA)>
        <!ATTLIST color
                name CDATA #REQUIRED>
        <!ELEMENT property (color)*>
        <!ATTLIST property
                default CDATA #REQUIRED
                name CDATA #REQUIRED
                src CDATA #REQUIRED>
        <!ELEMENT colorkeys (key)*>
        <!ELEMENT key (#PCDATA)>
        <!ATTLIST key
                base CDATA #REQUIRED
                src CDATA #REQUIRED
                transform CDATA #IMPLIED>
        <!ELEMENT spritemap (cell)*>
        <!ATTLIST spritemap
                file CDATA #REQUIRED>
        <!ELEMENT cell (#PCDATA)>
        <!ATTLIST cell
                dx CDATA #IMPLIED
                dy CDATA #IMPLIED
                name CDATA #REQUIRED
                rect CDATA #REQUIRED>
        <!ELEMENT layers (layer)*>
        <!ELEMENT layer (#PCDATA)>
        <!ATTLIST layer
                name CDATA #REQUIRED>
        <!ELEMENT logic (show|switch|if|hide|set)*>
        <!ELEMENT switch (case|default)*>
        <!ATTLIST switch
                value CDATA #IMPLIED>
        <!ELEMENT case (show|switch|if|hide|set)*>
        <!ATTLIST case
                test CDATA #IMPLIED
                value CDATA #IMPLIED
                values CDATA #IMPLIED>
        <!ELEMENT show (#PCDATA)>
        <!ATTLIST show
                part CDATA #REQUIRED>
        <!ELEMENT default (show|switch|if|hide|set)*>
        <!ELEMENT if (show|switch|if|hide|set|else)*>
        <!ATTLIST if
                test CDATA #REQUIRED>
        <!ELEMENT else (show|switch|if|hide|set)*>
        <!ELEMENT hide (#PCDATA)>
        <!ATTLIST hide
                part CDATA #REQUIRED>
        <!ELEMENT set (#PCDATA)>
        <!ATTLIST set
                var CDATA #REQUIRED
                value CDATA #IMPLIED>
        ]>
<!--suppress EqualityComparisonWithCoercionJS, CheckTagEmptyBody -->
<model name="demo" dir="./res/charview/" width="200" height="202" scale="2" originX="15" originY="10">
    <palette>
        <!--Colors common for skin/hair/fur/scales/... go here. Can be overriden later-->
        <common>
            <color name="albino">#f2f2e8</color>
            <color name="aqua">#00cccc</color>
            <color name="ashen">#817d79</color>
            <color name="ashen2">#9f948e</color>
            <color name="auburn">#732d26</color>
            <color name="black">#333333</color>
            <color name="blond">#e0c685</color>
            <color name="blonde">#f2e4bf</color>
            <color name="blue">#405fce</color>
            <color name="bronzed">#a89148</color>
            <color name="brown">#664400</color>
            <color name="caramel">#c39350</color>
            <color name="caramel2">#c38c50</color>
            <color name="cerulean">#59cfde</color>
            <color name="cerulean2">#377bc3</color>
            <color name="chocolate">#4a3b2b</color>
            <color name="crimson">#dc143c</color>
            <color name="crystal">#bc81ca</color>
            <color name="dark">#694e44</color>
            <color name="dark2">#352722</color>
            <color name="dusky">#f000f0</color>
            <color name="ebony">#3d3529</color>
            <color name="emerald">#4cc875</color>
            <color name="fair">#edccbf</color>
            <color name="golden">#ffdd00</color>
            <color name="gray">#808080</color>
            <color name="green">#08a108</color>
            <color name="indigo">#4d0080</color>
            <color name="light">#feebd7</color>
            <color name="mahogany">#81473b</color>
            <color name="mahogany2">#672828</color>
            <color name="metallic">#9c9c9c</color>
            <color name="midnight">#30354a</color>
            <color name="olive">#90974e</color>
            <color name="orange">#ffa600</color>
            <color name="peach">#f4c0a4</color>
            <color name="pink">#ffb3b3</color>
            <color name="purple">#7a007a</color>
            <color name="red">#f02c0a</color>
            <color name="red2">#ff0000</color>
            <color name="russet">#aa6546</color>
            <color name="russet2">#793939</color>
            <color name="sable">#d6caa9</color>
            <color name="sanguine">#c03030</color>
            <color name="silky">#ffd6ff</color>
            <color name="silver">#d8e0e9</color>
            <color name="tan">#af8750</color>
            <color name="tan2">#cfaa30</color>
            <color name="tawny">#b97f27</color>
            <color name="turquoise">#1ed9dc</color>
            <color name="white">#e6e6eb</color>
            <color name="yellow">#edef6b</color>
            <color name="aphotic blue-black">#08155e</color>
            <color name="ashen grayish-blue">#93b6c8</color>
            <color name="creamy-white">#f2ebde</color>
            <color name="crimson platinum">#d56c6c</color>
            <color name="dark blue">#3d529e</color>
            <color name="dark gray">#534f59</color>
            <color name="dark green">#36582d</color>
            <color name="deep blue">#1e3667</color>
            <color name="deep red">#742525</color>
            <color name="ghostly pale">#e3deed</color>
            <color name="glacial white">#dee5f2</color>
            <color name="golden blonde">#f5d88a</color>
            <color name="grayish-blue">#b0c9e3</color>
            <color name="iridescent gray">#999999</color>
            <color name="leaf green">#5eba5e</color>
            <color name="light blonde">#ffe78f</color>
            <color name="light blue">#b1c8ec</color>
            <color name="light gray">#dddadd</color>
            <color name="light green">#94f390</color>
            <color name="light grey">#c4d1d9</color>
            <color name="light purple">#e4cdf3</color>
            <color name="lime green">#73df72</color>
            <color name="mediterranean-toned">#ac7339</color>
            <color name="metallic golden">#ddc469</color>
            <color name="metallic silver">#cfedfc</color>
            <color name="midnight black">#171622</color>
            <color name="milky white">#f4dfdc</color>
            <color name="pale white">#ffeac7</color>
            <color name="pale yellow">#eeecaa</color>
            <color name="platinum blonde">#f7f3e8</color>
            <color name="platinum crimson">#ff745c</color>
            <color name="platinum-blonde">#ffe5c7</color>
            <color name="purplish-black">#794474</color>
            <color name="quartz white">#ffffff</color>
            <color name="reddish-orange">#df8453</color>
            <color name="rough gray">#525252</color>
            <color name="sandy blonde">#ebd69e</color>
            <color name="sandy brown">#a28d57</color>
            <color name="sandy-blonde">#e0cd9f</color>
            <color name="shiny black">#1c262c</color>
            <color name="silver blonde">#fcfaf8</color>
            <color name="silver-white">#eff3f6</color>
            <color name="snow white">#f9f9fa</color>
			<color name="ghastly white">#f9f9fa</color>
            <color name="yellowish-green">#e1eca7</color>
            <color name="black and yellow">#000000</color>
			<color name="abyssal black">#000000</color>
            <color name="white and black">#eff3f6</color>
        </common>
        <property name="hair" src="hairColor" default="#ffffff">
            <color name="red">#d85741</color>
            <color name="flaxen">#e1ba94</color>
            <color name="brown">#674f42</color>
            <color name="black">#334252</color>
            <color name="gray">#647a7d</color>
            <color name="white">#aeaba3</color>
            <color name="raven">#101728</color>
            <color name="snowy">#dddfe4</color>
        </property>
        <property name="hair2" src="hairColor" default="#ffffff"></property>
        <property name="fur" src="skin.coat.color" default="#ffffff"></property>
        <property name="fur2" src="skin.coat.color2" default="#ffffff"></property>
        <property name="scales" src="skin.coat.color" default="#ffffff"></property>
        <property name="scales2" src="skin.coat.color2" default="#ffffff"></property>
        <property name="chitin" src="skin.coat.color" default="#ffffff"></property>
        <property name="chitin2" src="skin.coat.color2" default="#ffffff"></property>
        <property name="skin" src="skinTone" default="#ffffff">
            <color name="pale">#f2e8e3</color>
        </property>
        <property name="skin2" src="skin.base.color2" default="#ffffff">
            <color name="pale">#f2e8e3</color>
        </property>
        <property name="iris" src="eyes.colour" default="#0000ff">
        </property>
    </palette>
    <colorkeys>
        <key src="#FF88FF" base="hair" transform="lighten(25)"/>
        <key src="#CC00CC" base="hair"/>
        <key src="#880088" base="hair" transform="darken(25)"/>
        <key src="#440044" base="hair" transform="darken(50)"/>
        <key src="#FFFF88" base="hair2" transform="lighten(25)"/>
        <key src="#CCCC00" base="hair2"/>
        <key src="#999900" base="hair2" transform="darken(25)"/>
        <key src="#333300" base="hair2" transform="darken(50)"/>
        <key src="#88FF88" base="fur" transform="lighten(25)"/>
        <key src="#00CC00" base="fur"/>
        <key src="#009900" base="fur" transform="darken(25)"/>
        <key src="#003300" base="fur" transform="darken(50)"/>
        <key src="#AA88FF" base="fur2" transform="lighten(25)"/>
        <key src="#6633CC" base="fur2"/>
        <key src="#442288" base="fur2" transform="darken(25)"/>
        <key src="#220044" base="fur2" transform="darken(50)"/>
        <key src="#8888FF" base="scales" transform="lighten(25)"/>
        <key src="#4444FF" base="scales"/>
        <key src="#0000CC" base="scales" transform="darken(25)"/>
        <key src="#000033" base="scales" transform="darken(50)"/>
        <key src="#AAFFAA" base="scales2" transform="lighten(25)"/>
        <key src="#66CC66" base="scales2"/>
        <key src="#448844" base="scales2" transform="darken(25)"/>
        <key src="#223322" base="scales2" transform="darken(50)"/>
        <key src="#88FFFF" base="chitin" transform="lighten(25)"/>
        <key src="#44CCFF" base="chitin"/>
        <key src="#0099CC" base="chitin" transform="darken(25)"/>
        <key src="#006666" base="chitin" transform="darken(50)"/>
        <key src="#AACCDD" base="chitin2" transform="lighten(25)"/>
        <key src="#77AACC" base="chitin2"/>
        <key src="#4477AA" base="chitin2" transform="darken(25)"/>
        <key src="#114477" base="chitin2" transform="darken(50)"/>
        <key src="#FFE9CC" base="skin" transform="lighten(25)"/>
        <key src="#FACE8D" base="skin"/>
        <key src="#BC9B6D" base="skin" transform="darken(25)"/>
        <key src="#7C6647" base="skin" transform="darken(50)"/>
        <key src="#1C0F0F" base="skin" transform="darken(75)"/>
        <key src="#FFCCCC" base="skin2" transform="lighten(25)"/>
        <key src="#FF9999" base="skin2"/>
        <key src="#BB7777" base="skin2" transform="darken(25)"/>
        <key src="#884444" base="skin2" transform="darken(50)"/>
        <key src="#221111" base="skin2" transform="darken(75)"/>
		<key src="#FF0000" base="iris"/>
		<key src="#AA0000" base="iris" transform="darken(25)"/>
        <key src="#FBCAAE" base="skin" transform="darken(25);saturate(25);shiftTo(0,25,25)"/>
        <!--<key src="#FFFFFF" base="sclera"/>-->
        <!--<key src="#0026FF" base="iris"/>-->
    </colorkeys>
    <!--<spritesheet file="char1.png" cellwidth="192" cellheight="192">
        <row>name1,name2,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,breasts/Dfur,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
        <row>,,,,,,,,,,,,,,</row>
    </spritesheet>-->


	<!-- LOCATION IN SCREEN AREA -->
        <spritemap file="body.png">
        <cell rect="1,90,49,59" name="torso/human" dx="69" dy="64"/>
        <cell rect="51,90,49,59" name="torso/fur" dx="69" dy="64"/>
        <cell rect="101,90,49,59" name="torso/chitin" dx="69" dy="64"/>
        <cell rect="151,90,49,59" name="torso/bee" dx="69" dy="64"/>
        <cell rect="201,90,49,59" name="torso/orca" dx="69" dy="64"/>
        <cell rect="251,90,49,59" name="torso/pscales" dx="69" dy="64"/>
        <cell rect="301,90,49,59" name="torso/scales" dx="69" dy="64"/>
        <cell rect="351,90,49,59" name="torso/goo" dx="69" dy="64"/>
        <cell rect="401,90,49,59" name="torso/kraken" dx="69" dy="64"/>
        <cell rect="601,90,49,59" name="torso/panda" dx="69" dy="64"/>
        <cell rect="451,90,49,59" name="torso_pattern/Bstripe" dx="69" dy="64"/>
        <cell rect="501,90,49,59" name="torso_pattern/Blightning" dx="69" dy="64"/>
        <cell rect="551,90,49,59" name="torso_pattern/Btatoo" dx="69" dy="64"/>
        <cell rect="1,150,49,59" name="arms_bg/human" dx="46" dy="64"/>
        <cell rect="51,150,49,59" name="arms_bg/fur" dx="46" dy="64"/>
        <cell rect="551,150,49,59" name="arms_bg/furracoon" dx="46" dy="64"/>
        <cell rect="101,150,49,59" name="arms_bg/chitin" dx="46" dy="64"/>
        <cell rect="151,150,49,59" name="arms_bg/bee" dx="46" dy="64"/>
        <cell rect="201,150,49,59" name="arms_bg/chitin2" dx="46" dy="64"/>
        <cell rect="251,150,49,59" name="arms_bg/orca" dx="46" dy="64"/>
        <cell rect="301,150,49,59" name="arms_bg/pscales" dx="46" dy="64"/>
        <cell rect="351,150,49,59" name="arms_bg/scales" dx="46" dy="64"/>
        <cell rect="401,150,49,59" name="arms_bg/goo" dx="46" dy="64"/>
        <cell rect="701,150,49,59" name="arms_bg/panda" dx="46" dy="64"/>
        <cell rect="801,150,49,59" name="arms_bg/demonlewd" dx="46" dy="64"/>
        <cell rect="1,853,49,59" name="arms_bg/displacerquad_human" dx="46" dy="56"/>
        <cell rect="51,853,49,59" name="arms_bg/displacerquad_fur" dx="46" dy="56"/>
        <cell rect="101,853,49,59" name="arms_bg/displacerquad_scales" dx="46" dy="56"/>
        <cell rect="151,853,49,59" name="arms_bg/displacerquad_pscales" dx="46" dy="56"/>
        <cell rect="201,853,49,59" name="arms_bg/displacerquad_chitin" dx="46" dy="56"/>
        <cell rect="251,853,49,59" name="arms_bg/displacerquad_orca" dx="46" dy="56"/>
        <cell rect="1,1064,49,59" name="arms_bg/feral_human" dx="46" dy="56"/>
        <cell rect="51,1064,49,59" name="arms_bg/feral_fur" dx="46" dy="56"/>
        <cell rect="101,1064,49,59" name="arms_bg/feral_scales" dx="46" dy="56"/>
        <cell rect="151,1064,49,59" name="arms_bg/feral_pscales" dx="46" dy="56"/>
        <cell rect="201,1064,49,59" name="arms_bg/feral_chitin" dx="46" dy="56"/>
        <cell rect="251,1064,49,59" name="arms_bg/feral_orca" dx="46" dy="56"/>
        <cell rect="451,150,49,59" name="arms_bg_pattern/Bstripe" dx="46" dy="64"/>
        <cell rect="501,150,49,59" name="arms_bg_pattern/Blightning" dx="46" dy="64"/>
        <cell rect="601,150,49,59" name="arms_bg_pattern/Btatoo" dx="46" dy="64"/>
        <cell rect="1,210,49,59" name="arms/human" dx="94" dy="64"/>
        <cell rect="51,210,49,59" name="arms/fur" dx="94" dy="64"/>
        <cell rect="551,210,49,59" name="arms/furracoon" dx="94" dy="64"/>
        <cell rect="101,210,49,59" name="arms/chitin" dx="94" dy="64"/>
        <cell rect="151,210,49,59" name="arms/bee" dx="94" dy="64"/>
        <cell rect="201,210,49,59" name="arms/chitin2" dx="94" dy="64"/>
        <cell rect="251,210,49,59" name="arms/orca" dx="94" dy="64"/>
        <cell rect="301,210,49,59" name="arms/pscales" dx="94" dy="64"/>
        <cell rect="351,210,49,59" name="arms/scales" dx="94" dy="64"/>
        <cell rect="401,210,49,59" name="arms/goo" dx="94" dy="64"/>
        <cell rect="701,210,49,59" name="arms/panda" dx="94" dy="64"/>
        <cell rect="638,520,90,90" name="arms/yeti" dx="47" dy="43"/>
        <cell rect="1,702,90,90" name="arms/manticore_sit" dx="50" dy="61"/>
        <cell rect="92,702,90,90" name="arms/manticore_sit_fur" dx="50" dy="61"/>
        <cell rect="183,702,90,90" name="arms/manticore_sit_scales" dx="50" dy="61"/>
        <cell rect="274,702,90,90" name="arms/manticore_sit_pscales" dx="50" dy="61"/>
        <cell rect="365,702,90,90" name="arms/manticore_sit_chitin" dx="50" dy="61"/>
        <cell rect="456,702,90,90" name="arms/manticore_sit_orca" dx="50" dy="61"/>
        <cell rect="547,702,90,90" name="arms/gargoyle_sit" dx="50" dy="61"/>
        <cell rect="1,913,49,59" name="arms/displacerquad_human" dx="91" dy="56"/>
        <cell rect="51,913,49,59" name="arms/displacerquad_fur" dx="91" dy="56"/>
        <cell rect="101,913,49,59" name="arms/displacerquad_scales" dx="91" dy="56"/>
        <cell rect="151,913,49,59" name="arms/displacerquad_pscales" dx="91" dy="56"/>
        <cell rect="201,913,49,59" name="arms/displacerquad_chitin" dx="91" dy="56"/>
        <cell rect="251,913,49,59" name="arms/displacerquad_orca" dx="91" dy="56"/>
        <cell rect="1,1124,49,59" name="arms/feral_human" dx="91" dy="56"/>
        <cell rect="51,1124,49,59" name="arms/feral_fur" dx="91" dy="56"/>
        <cell rect="101,1124,49,59" name="arms/feral_scales" dx="91" dy="56"/>
        <cell rect="151,1124,49,59" name="arms/feral_pscales" dx="91" dy="56"/>
        <cell rect="201,1124,49,59" name="arms/feral_chitin" dx="91" dy="56"/>
        <cell rect="251,1124,49,59" name="arms/feral_orca" dx="91" dy="56"/>
        <cell rect="801,210,49,59" name="arms/demonlewd" dx="88" dy="54"/>
        <cell rect="1,1184,99,119" name="arms/hinezumistanced_human" dx="48" dy="55"/>
        <cell rect="101,1184,99,119" name="arms/hinezumistanced_fur" dx="48" dy="55"/>
        <cell rect="201,1184,99,119" name="arms/hinezumistanced_scales" dx="48" dy="55"/>
        <cell rect="301,1184,99,119" name="arms/hinezumistanced_pscales" dx="48" dy="55"/>
        <cell rect="401,1184,99,119" name="arms/hinezumistanced_chitin" dx="48" dy="55"/>
        <cell rect="501,1184,99,119" name="arms/hinezumistanced_orca" dx="48" dy="55"/>
        <cell rect="851,210,49,59" name="arms_fg/demonlewd" dx="88" dy="54"/>
        <cell rect="451,210,49,59" name="arms_pattern/Bstripe" dx="94" dy="64"/>
        <cell rect="501,210,49,59" name="arms_pattern/Blightning" dx="94" dy="64"/>
        <cell rect="651,210,49,59" name="arms_pattern/Btatoo" dx="94" dy="64"/>
        <cell rect="1,270,49,59" name="hands_bg/fur" dx="46" dy="64"/>
        <cell rect="601,270,49,59" name="hands_bg/furracoon" dx="46" dy="64"/>
        <cell rect="51,270,49,59" name="hands_bg/devil" dx="46" dy="64"/>
        <cell rect="101,270,49,59" name="hands_bg/harpy" dx="46" dy="64"/>
        <cell rect="151,270,49,59" name="hands_bg/kraken" dx="46" dy="64"/>
        <cell rect="201,270,49,59" name="hands_bg/alraune" dx="46" dy="64"/>
        <cell rect="251,270,49,59" name="hands_bg/chitin" dx="46" dy="64"/>
        <cell rect="301,270,49,59" name="hands_bg/chitin2" dx="46" dy="64"/>
        <cell rect="351,270,49,59" name="hands_bg/fire" dx="46" dy="64"/>
        <cell rect="401,270,49,59" name="hands_bg/scales" dx="46" dy="64"/>
        <cell rect="451,270,49,59" name="hands_bg/human" dx="46" dy="64"/>
        <cell rect="501,270,49,59" name="hands_bg/fins-orca" dx="46" dy="64"/>
        <cell rect="551,270,49,59" name="hands_bg/goo" dx="46" dy="64"/>
        <cell rect="701,270,49,59" name="hands_bg/panda" dx="46" dy="64"/>
        <cell rect="301,1064,49,59" name="hand_bg/kumiho" dx="46" dy="56"/>
        <cell rect="851,150,49,59" name="hands_bg/wraithleft" dx="53" dy="75"/>
        <cell rect="351,270,49,59" name="overhands_bg/fire" dx="46" dy="64"/>
        <cell rect="1,330,49,59" name="hands/fur" dx="94" dy="64"/>
        <cell rect="601,330,49,59" name="hands/furracoon" dx="94" dy="64"/>
        <cell rect="51,330,49,59" name="hands/devil" dx="94" dy="64"/>
        <cell rect="101,330,49,59" name="hands/harpy" dx="94" dy="64"/>
        <cell rect="151,330,49,59" name="hands/kraken" dx="94" dy="64"/>
        <cell rect="201,330,49,59" name="hands/alraune" dx="94" dy="64"/>
        <cell rect="251,330,49,59" name="hands/chitin" dx="94" dy="64"/>
        <cell rect="301,330,49,59" name="hands/chitin2" dx="94" dy="64"/>
        <cell rect="401,330,49,59" name="hands/scales" dx="94" dy="64"/>
        <cell rect="451,330,49,59" name="hands/human" dx="94" dy="64"/>
        <cell rect="501,330,49,59" name="hands/fins-orca" dx="94" dy="64"/>
        <cell rect="551,330,49,59" name="hands/goo" dx="94" dy="64"/>
        <cell rect="701,330,49,59" name="hands/panda" dx="94" dy="64"/>
        <cell rect="729,520,90,90" name="hands/yeti" dx="47" dy="43"/>
        <cell rect="301,1124,49,59" name="hands/kumiho" dx="91" dy="56"/>
        <cell rect="901,210,49,59" name="hands/wraithright" dx="84" dy="75"/>
        <cell rect="951,210,49,59" name="hands_fg/wraithrightlewd" dx="95" dy="48"/>
        <cell rect="351,330,49,59" name="overhands/fire" dx="94" dy="64"/>
        <cell rect="1,390,49,59" name="legs/human" dx="69" dy="115"/>
        <cell rect="51,390,49,59" name="legs/fur" dx="69" dy="115"/>
        <cell rect="101,390,49,59" name="legs/chitin" dx="69" dy="115"/>
        <cell rect="151,390,49,59" name="legs/chitin2" dx="69" dy="115"/>
        <cell rect="201,390,49,59" name="legs/orca" dx="69" dy="115"/>
        <cell rect="251,390,49,59" name="legs/pscales" dx="69" dy="115"/>
        <cell rect="301,390,49,59" name="legs/scales" dx="69" dy="115"/>
        <cell rect="351,390,49,59" name="legs/hoof_human" dx="69" dy="115"/>
        <cell rect="1,793,49,59" name="legs/hoof_fur" dx="69" dy="115"/>
        <cell rect="51,793,49,59" name="legs/hoof_scales" dx="69" dy="115"/>
        <cell rect="101,793,49,59" name="legs/hoof_pscales" dx="69" dy="115"/>
        <cell rect="151,793,49,59" name="legs/hoof_chitin" dx="69" dy="115"/>
        <cell rect="201,793,49,59" name="legs/hoof_orca" dx="69" dy="115"/>
        <cell rect="1,520,90,90" name="legs/harpy_human" dx="50" dy="99"/>
        <cell rect="92,520,90,90" name="legs/harpy_fur" dx="50" dy="99"/>
        <cell rect="183,520,90,90" name="legs/harpy_scales" dx="50" dy="99"/>
        <cell rect="274,520,90,90" name="legs/harpy_pscales" dx="50" dy="99"/>
        <cell rect="365,520,90,90" name="legs/harpy_chitin" dx="50" dy="99"/>
        <cell rect="456,520,90,90" name="legs/harpy_orca" dx="50" dy="99"/>
        <cell rect="547,520,90,90" name="legs/demonlewd" dx="50" dy="99"/>
        <cell rect="1,973,90,90" name="legs/displacer_human" dx="52" dy="68"/>
        <cell rect="92,973,90,90" name="legs/displacer_fur" dx="52" dy="68"/>
        <cell rect="183,973,90,90" name="legs/displacer_scales" dx="52" dy="68"/>
        <cell rect="274,973,90,90" name="legs/displacer_pscales" dx="52" dy="68"/>
        <cell rect="365,973,90,90" name="legs/displacer_chitin" dx="52" dy="68"/>
        <cell rect="456,973,90,90" name="legs/displacer_orca" dx="52" dy="68"/>
        <cell rect="401,390,49,59" name="legs/goo" dx="69" dy="115"/>
        <cell rect="551,390,49,59" name="legs/furracoon" dx="69" dy="115"/>
        <cell rect="651,390,49,59" name="legs/panda" dx="69" dy="115"/>
        <cell rect="1,611,90,90" name="legs/manticore_sit" dx="50" dy="61"/>
        <cell rect="92,611,90,90" name="legs/manticore_sit_fur" dx="50" dy="61"/>
        <cell rect="183,611,90,90" name="legs/manticore_sit_scales" dx="50" dy="61"/>
        <cell rect="274,611,90,90" name="legs/manticore_sit_pscales" dx="50" dy="61"/>
        <cell rect="365,611,90,90" name="legs/manticore_sit_chitin" dx="50" dy="61"/>
        <cell rect="547,611,90,90" name="legs/gargoyle_sit" dx="50" dy="61"/>
        <cell rect="451,390,49,59" name="legs_pattern/Bstripe" dx="69" dy="115"/>
        <cell rect="501,390,49,59" name="legs_pattern/Blightning" dx="69" dy="115"/>
        <cell rect="601,390,49,59" name="legs_pattern/Btatoo" dx="69" dy="115"/>
        <cell rect="51,450,49,59" name="feet/fur" dx="68" dy="115"/>
        <cell rect="101,450,49,59" name="feet/scales" dx="69" dy="115"/>
        <cell rect="551,450,49,59" name="feet/furracoon" dx="69" dy="115"/>
        <cell rect="601,450,49,59" name="feet/alraune" dx="68" dy="115"/>
        <cell rect="651,450,49,59" name="feet/panda" dx="69" dy="115"/>
        <cell rect="751,390,49,59" name="feet/yeti" dx="69" dy="115"/>
        <cell rect="547,973,90,90" name="feet/kumiho" dx="52" dy="68"/>
        <cell rect="638,611,90,90" name="feet/bunny" dx="49" dy="92"/>
        <cell rect="151,450,49,59" name="overfeet/fire" dx="69" dy="115"/>
        <cell rect="701,90,49,59" name="muscle/muscle" dx="69" dy="64"/>
    </spritemap>
    <spritemap file="extra.png">
        <cell rect="2,55,147,128" name="legs_fg/alraune" dx="24" dy="82"/>
        <cell rect="1,188,173,156" name="legs_fg/liliraune" dx="-3" dy="58"/>
        <cell rect="9,351,175,119" name="legs_fg/drider" dx="21" dy="64"/>
        <cell rect="463,101,143,107" name="legs_fg/centaur" dx="47" dy="93"/>
        <cell rect="255,230,125,88" name="legs_fg/cattaur" dx="71" dy="103"/>
        <cell rect="381,230,125,88" name="legs_fg/reptaur" dx="71" dy="103"/>
        <cell rect="370,445,125,88" name="legs_fg/pandataur" dx="71" dy="103"/>
        <cell rect="370,534,125,88" name="legs_fg/beartaur" dx="71" dy="103"/>
        <cell rect="272,12,125,88" name="legs_fg/aquataur" dx="71" dy="103"/>
        <cell rect="122,798,173,156" name="legs_fg/hydra2" dx="19" dy="47"/>
        <cell rect="296,798,173,156" name="legs_fg/hydra3" dx="19" dy="47"/>
        <cell rect="470,798,173,156" name="legs_fg/hydra4" dx="19" dy="47"/>
        <cell rect="122,956,173,156" name="legs_fg/hydra5" dx="19" dy="47"/>
        <cell rect="296,956,173,156" name="legs_fg/hydra6" dx="19" dy="47"/>
        <cell rect="371,325,175,119" name="legs_fg/crabtaur" dx="22" dy="65"/>
        <cell rect="546,325,175,119" name="legs_fg/bugtaur" dx="22" dy="65"/>
        <cell rect="607,101,143,107" name="legs/centaur" dx="47" dy="93"/>
        <cell rect="507,230,125,88" name="legs/cattaur" dx="71" dy="103"/>
        <cell rect="633,230,125,88" name="legs/reptaur" dx="71" dy="103"/>
        <cell rect="496,445,125,88" name="legs/pandataur" dx="71" dy="103"/>
        <cell rect="496,534,125,88" name="legs/beartaur" dx="71" dy="103"/>
        <cell rect="398,12,125,88" name="legs/aquataur" dx="71" dy="103"/>
        <cell rect="131,491,117,117" name="legs/scylla" dx="35" dy="94"/>
        <cell rect="251,450,118,158" name="legs/kraken" dx="34" dy="54"/>
        <cell rect="201,101,130,108" name="legs/naga" dx="32" dy="97"/>
        <cell rect="239,325,130,108" name="legs/ghost" dx="32" dy="97"/>
        <cell rect="332,101,130,108" name="legs/melkie" dx="45" dy="95"/>
        <cell rect="132,611,125,69" name="legs/gooblob" dx="31" dy="102"/>
        <cell rect="1013,101,130,108" name="legs/wraith" dx="32" dy="97"/>
        <cell rect="122,1114,173,156" name="legs_bg/hydra2" dx="19" dy="47"/>
        <cell rect="296,1114,173,156" name="legs_bg/hydra3" dx="19" dy="47"/>
        <cell rect="470,1114,173,156" name="legs_bg/hydra4" dx="19" dy="47"/>
        <cell rect="122,1272,173,156" name="legs_bg/hydra5" dx="19" dy="47"/>
        <cell rect="296,1272,173,156" name="legs_bg/hydra6" dx="19" dy="47"/>
        <cell rect="470,956,173,156" name="fullbody/femalejiangshi" dx="6" dy="23"/>
        <cell rect="470,1272,173,156" name="fullbody/malejiangshi" dx="6" dy="23"/>
        <cell rect="260,620,21,28" name="neck/goocore" dx="85" dy="67"/>
        <cell rect="162,59,54,31" name="neck/manticore" dx="67" dy="47"/>
        <cell rect="217,59,54,31" name="neck/weasel" dx="67" dy="50"/>
        <cell rect="217,27,54,31" name="rearbody/shark" dx="74" dy="72"/>
        <cell rect="470,641,173,156" name="aura/ghostlyaura" dx="11" dy="28"/>
        <cell rect="644,641,173,156" name="aura/wraithaura" dx="11" dy="28"/>
        <cell rect="818,641,173,156" name="aura/thunderaura" dx="11" dy="28"/>
        <cell rect="525,12,115,88" name="clothe/scarf" dx="64" dy="32"/>
        <cell rect="751,101,125,105" name="clothe/blizzardtop" dx="39" dy="72"/>
        <cell rect="882,101,125,105" name="clothe/blizzardbottom" dx="39" dy="72"/>
    </spritemap>
    <spritemap file="hair.png">
        <cell rect="1,70,59,65" name="hair/0" dx="65" dy="21"/>
        <cell rect="1,136,59,65" name="hair_bg/0" dx="65" dy="21"/>
        <cell rect="361,350,89,98" name="hair_bg/02" dx="50" dy="5"/>
        <cell rect="61,70,59,65" name="hair/feather" dx="65" dy="21"/>
        <cell rect="61,136,59,65" name="hair_bg/feather" dx="65" dy="21"/>
        <cell rect="121,70,59,65" name="hair/gorgon" dx="65" dy="21"/>
        <cell rect="121,136,59,65" name="hair_bg/gorgon" dx="65" dy="21"/>
        <cell rect="1,251,89,98" name="hair/slime" dx="50" dy="4"/>